blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path(
        route='tag/<slug:tag_slug>/',
        view=views.post_list,
        name='post_list_by_tag'
    ),
    path(
        route='<int:year>/<int:month>/<int:day>/<slug:post>/',
        view=views.post_detail,
        name='post_detail'
    ),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path(route='', view=views.cart_detail, name='cart_detail'),
    path(route='add/<int:product_id>/', view=views.cart_add, name='cart_add'),
    path(
        route='update/<int:product_id>/',
        view=views.cart_update,
        name='cart_update'
    ),
    path(
        route='remove/<int:product_id>/',
        view=views.cart_remove,
        name='cart_remove'
    )
]

coupons/urls.py
from django.urls import path

from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path(route='create/', view=views.order_create, name='order_create'),
    path(
        route='admin/order/<int:order_id>/',
        view=views.admin_order_detail,
        name='admin_order_detail'
    ),
    path(
        route='admin/order/<int:order_id>/pdf/',
        view=views.admin_order_pdf,
        name='admin_order_pdf'
    )
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path(route='', view=views.index, name='index'),
    path(
        route='shop/',
        view=views.product_list,
        name='product_list'
    ),
    path(
        route='shop/<slug:category_slug>/',
        view=views.product_list,
        name='product_list_by_category'
    ),
    path(
        route='<int:id>/<slug:slug>/',
        view=views.product_detail,
        name='product_detail'
    ),
    path(
        route='products/search/',
        view=views.product_search,
        name='product_search'
    )
]

shopily/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from payment import webhooks

from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(route=_('cart/'), view=include('cart.urls', namespace='cart')),
    path(route=_('orders/'), view=include('orders.urls', namespace='orders')),
    path(route=_('payment/'), view=include('payment.urls', namespace='payment')),
    path(route=_('coupons/'), view=include('coupons.urls', namespace='coupons')),
    path(route=_('blog/'), view=include('blog.urls', namespace='blog')),
    path(route=_('accounts/'), view=include('accounts.urls', namespace='accounts')),
    path(route='rosetta/', view=include('rosetta.urls')),
    path(route='', view=include('shop.urls', namespace='shop')),
)

urlpatterns += [
    path('payment/webhook/', webhooks.stripe_webhook, name='stripe-webhook'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [
    (i, str(i)) for i in range(1, 21)
]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.urls import reverse
from decimal import Decimal
import json

from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm

# Create your views here.


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cleaned_data = form.cleaned_data
        cart.add(
            product=product,
            quantity=cleaned_data['quantity'],
            override_quantity=cleaned_data['override']
        )
        # handle POST request from ajax call
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({'redirect': True, 'redirect_url': reverse('cart:cart_detail')})
        else:
            # in case you use form to submit request instead of ajax
            return redirect('cart:cart_detail')


@require_POST
def cart_update(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    quantity = int(json.loads(request.body)['quantity'])

    cart.add(
        product=product,
        quantity=quantity,
        override_quantity=True
    )

    cart_subtotal = round(cart.get_total_price(), 2)
    cart_discount = round(cart.get_discount(), 2)
    cart_total = round(cart.get_total_price_after_discount(), 2)
    updated_item_quantity = cart.cart.get(
        str(product_id), {}).get('quantity', 0)
    updated_item_total_price = quantity * Decimal(product.price)
    cart_total_items_count = len(cart)

    return JsonResponse({
        'cartSubtotalPrice': str(cart_subtotal),
        'cartDiscount': str(cart_discount),
        'cartTotalPrice': str(cart_total),
        'updatedItemQuantity': updated_item_quantity,
        'updatedItemTotalPrice': str(updated_item_total_price),
        'cartTotalItems': cart_total_items_count,
        'success': True
    })


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    coupon_apply_form = CouponApplyForm()

    return render(request=request, template_name='cart/detail.html', context={'cart': cart, 'section': 'shop', 'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}
    Your shopping cart
{% endblock title %}

{% block breadcrumb %}
    shopping cart
{% endblock breadcrumb %}

{% block content %}
    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th class="shoping__product">Products</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                    {% with product=item.product %}
                                        <tr>
                                            <td class="shoping__cart__item">
                                                <img src="{% thumbnail product.image 60x60 crop %}" alt="">
                                                <h5>{{ product.name }}</h5>
                                            </td>
                                            <td class="shoping__cart__price" id="product-price">${{ item.price }}</td>
                                            <td class="shoping__cart__quantity">
                                                <div class="quantity">
                                                    <div class="pro-qty">
                                                        <input type="text"
                                                               value="{{ item.quantity }}"
                                                               id="item-input-quantity-{{ product.id }}"
                                                               class="quantity-input"
                                                               min="1"
                                                               max="20"
                                                               data-product-id="{{ product.id }}"
                                                               readonly>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="shoping__cart__total" id="item-total-price-{{ product.id }}">${{ item.total_price }}</td>
                                            <td class="shoping__cart__item__close">
                                                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                                    <input type="submit" value="Remove" class="btn btn-danger">
                                                    {% csrf_token %}
                                                </form>
                                            </td>
                                        </tr>
                                    {% endwith %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__btns">
                        <a href="{% url "shop:product_list" %}"
                           class="primary-btn cart-btn cart-btn-right">CONTINUE SHOPPING</a>
                    </div>
                </div>
                {% if cart|length > 0 %}
                    <div class="col-lg-6">
                        <div class="shoping__continue">
                            <div class="shoping__discount">
                                <h5>Discount Codes</h5>
                                <form action="{% url "coupons:apply" %}" method="post">
                                    {{ coupon_apply_form.code }}
                                    {% if coupon_apply_form.code.errors %}<div class="error">{{ coupon_apply_form.code.errors.as_text }}</div>{% endif %}
                                    <button type="submit" class="site-btn">APPLY COUPON</button>
                                    {% csrf_token %}
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="shoping__checkout">
                            <h5>Cart Total</h5>
                            <ul>
                                <li>
                                    Subtotal <span id="cart-subtotal">${{ cart.get_total_price|floatformat:2 }}</span>
                                </li>
                                {% if cart.coupon %}
                                    <li>
                                        Discount ({{ cart.coupon.discount }}% off) <span id="cart-discount">- ${{ cart.get_discount|floatformat:2 }}</span>
                                    </li>
                                {% endif %}
                                <li>
                                    Total <span id="cart-total">${{ cart.get_total_price_after_discount|floatformat:2 }}</span>
                                </li>
                            </ul>
                            <a href="{% url "orders:order_create" %}" class="primary-btn">PROCEED TO CHECKOUT</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </section>
    <!-- Shoping Cart Section End -->
{% endblock content %}