blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path(
        route='tag/<slug:tag_slug>/',
        view=views.post_list,
        name='post_list_by_tag'
    ),
    path(
        route='<int:year>/<int:month>/<int:day>/<slug:post>/',
        view=views.post_detail,
        name='post_detail'
    ),
]

shopily/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from payment import webhooks

from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(route=_('cart/'), view=include('cart.urls', namespace='cart')),
    path(route=_('orders/'), view=include('orders.urls', namespace='orders')),
    path(route=_('payment/'), view=include('payment.urls', namespace='payment')),
    path(route=_('coupons/'), view=include('coupons.urls', namespace='coupons')),
    path(route=_('blog/'), view=include('blog.urls', namespace='blog')),
    path(route=_('accounts/'), view=include('accounts.urls', namespace='accounts')),
    path(route='rosetta/', view=include('rosetta.urls')),
    path(route='', view=include('shop.urls', namespace='shop')),
)

urlpatterns += [
    path('payment/webhook/', webhooks.stripe_webhook, name='stripe-webhook'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse

from taggit.managers import TaggableManager
# Create your models here.


class PublishedManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='blog_posts'
    )
    body = models.TextField()
    image = models.ImageField(upload_to='blog/%Y/%m/%d', blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT
    )
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse(
            viewname="blog:post_detail",
            kwargs={
                'year': self.publish.year,
                'month': self.publish.month,
                'day': self.publish.day,
                'post': self.slug
            }
        )

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Count

from .models import Post

from taggit.models import Tag

# Create your views here.


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    recent_three_posts = post_list[:3]
    tags = Tag.objects.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    # pagination with 4 blog post per page
    paginator = Paginator(object_list=post_list, per_page=4)
    page_number = request.GET.get('page', 1)
    posts = paginator.page(number=page_number)

    return render(
        request,
        'blog/post/list.html',
        {
            # this posts is the main list of post which contains pagination
            'posts': posts,
            'tags': tags,
            'section': 'blog',
            'posts_count': len(post_list),
            'recent_three_posts': recent_three_posts,
            'tag': tag
        }
    )


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        klass=Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day
    )

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')
    ).order_by('-same_tags', '-publish')[:3]

    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'section': 'blog_detail',
            'similar_posts': similar_posts
        }
    )

blog/templates/blog/post/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block breadcrumb %}
    {{ post.title }}
{% endblock breadcrumb %}

{% block breadcrumb_subtext %}
    <ul>
        <li>By {{ post.author|title }}</li>
        <li>{{ post.publish }}</li>
    </ul>
{% endblock breadcrumb_subtext %}

{% block content %}
    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div>
                <div class="blog__details__text">
                    <img src="{{ post.image.url }}" alt="">
                    <p>{{ post.body|linebreaksbr }}</p>
                </div>
                <div class="blog__details__content">
                    <div class="row align-items-center">
                        <div class="col-lg-6">
                            <div class="blog__details__author">
                                <div class="blog__details__author__pic">
                                    <img src="{% static "img/no_image.png" %}" alt="">
                                </div>
                                <div class="blog__details__author__text">
                                    <h6>{{ post.author }}</h6>
                                    <span>Admin</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="blog__details__widget">
                                <ul>
                                    {% if post.tags.all|length > 0 %}
                                        <li>
                                            <span>Tags:</span> {{ post.tags.all|join:", " }}
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Section End -->

    <!-- Related Blog Section Begin -->
    {% if similar_posts|length > 0 %}
        <section class="related-blog spad">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-title related-blog-title">
                            <h2>Post You May Like</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for post in similar_posts %}
                        <div class="col-lg-4 col-md-4 col-sm-6">
                            <div class="blog__item">
                                <div class="blog__item__pic">
                                    <img src="{% if post.image %}{% thumbnail post.image 360x360 crop %}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
                                </div>
                                <div class="blog__item__text">
                                    <ul>
                                        <li>
                                            <i class="fa fa-calendar-o"></i> {{ post.publish }}
                                        </li>
                                    </ul>
                                    <h5>
                                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                    </h5>
                                    <p>{{ post.body|truncatechars:80|linebreaks }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}
    <!-- Related Blog Section End -->
{% endblock content %}

blog/templates/blog/post/list.html
{% extends "shop/base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}
    Blog
{% endblock title %}

{% block breadcrumb %}
    {% if tag %}
        Posts tagged with "{{ tag.name }}"
    {% else %}
        Blog
    {% endif %}
{% endblock breadcrumb %}

{% block content %}
    <!-- Blog Section Begin -->
    <section class="blog spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-5">
                    <div class="blog__sidebar">
                        <div class="blog__sidebar__item">
                            <h4>Recent News</h4>
                            <div class="blog__sidebar__recent">
                                {% for post in recent_three_posts %}
                                    <a href="{{ post.get_absolute_url }}"
                                       class="blog__sidebar__recent__item">
                                        <div class="blog__sidebar__recent__item__pic">
                                            <img src="{% thumbnail post.image 60x60 crop %}" alt="">
                                        </div>
                                        <div class="blog__sidebar__recent__item__text">
                                            <h6>{{ post.title }}</h6>
                                            <span>{{ post.publish }}</span>
                                        </div>
                                    </a>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="blog__sidebar__item">
                            <h4>Search By</h4>
                            <div class="blog__sidebar__item__tags">
                                <a href="{% url "blog:post_list" %}">All</a>
                                {% for tag in tags %}
                                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8 col-md-7">
                    <div class="row">
                        {% for post in posts %}
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="blog__item">
                                    <div class="blog__item__pic">
                                        <img src="{% if post.image %}{% thumbnail post.image 360x360 crop %}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
                                    </div>
                                    <div class="blog__item__text">
                                        <ul>
                                            <li>
                                                <i class="fa fa-calendar-o"></i> {{ post.publish }}
                                            </li>
                                        </ul>
                                        <h5>
                                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                        </h5>
                                        <p>{{ post.body|truncatechars:80|linebreaks }}</p>
                                        <a href="{{ post.get_absolute_url }}" class="blog__btn">READ MORE <span class="arrow_right"></span></a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        {% if posts_count > 4 %}
                            <div class="col-lg-12">{% include "shop/pagination.html" with page=posts %}</div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Section End -->
{% endblock content %}