blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path(
        route='tag/<slug:tag_slug>/',
        view=views.post_list,
        name='post_list_by_tag'
    ),
    path(
        route='<int:year>/<int:month>/<int:day>/<slug:post>/',
        view=views.post_detail,
        name='post_detail'
    ),
]

payment/urls.py
from django.urls import path

from . import views
from . import webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
]

shopily/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from payment import webhooks

from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(route=_('cart/'), view=include('cart.urls', namespace='cart')),
    path(route=_('orders/'), view=include('orders.urls', namespace='orders')),
    path(route=_('payment/'), view=include('payment.urls', namespace='payment')),
    path(route=_('coupons/'), view=include('coupons.urls', namespace='coupons')),
    path(route=_('blog/'), view=include('blog.urls', namespace='blog')),
    path(route=_('accounts/'), view=include('accounts.urls', namespace='accounts')),
    path(route='rosetta/', view=include('rosetta.urls')),
    path(route='', view=include('shop.urls', namespace='shop')),
)

urlpatterns += [
    path('payment/webhook/', webhooks.stripe_webhook, name='stripe-webhook'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

payment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from decimal import Decimal
from django.conf import settings

import stripe

from orders.models import Order

# Create your views here.
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


@login_required
def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)
    # this variable and other variables will automatically be passed to the render context because of the locals()
    section = 'shop'

    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))

        # Stripe checkout session data
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }

        # add order items to the Stripe checkout session
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'usd',
                    'product_data': {
                        'name': item.product.name,
                    }
                },
                'quantity': item.quantity,
            })

        # Stripe coupon
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                name=order.coupon.code,
                percent_off=order.discount,
                duration='once'
            )

            session_data['discounts'] = [{
                'coupon': stripe_coupon.id
            }]

        # create Stripe checkout session
        session = stripe.checkout.Session.create(**session_data)

        # redirect to Stripe payment form
        return redirect(session.url, code=303)

    else:
        return render(request, 'payment/process.html', locals())


def payment_completed(request):
    return render(request, 'payment/completed.html', {'section': 'shop'})


def payment_canceled(request):
    return render(request, 'payment/canceled.html', {'section': 'shop'})

payment/templates/payment/canceled.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Payment canceled
{% endblock title %}

{% block breadcrumb %}
    Payment Incomplete
{% endblock breadcrumb %}

{% block content %}
    <div class="container text-center mt-5">
        <h1 class="mb-4 text-danger">Your payment has not been processed</h1>
        <p class="text-warning">There was a problem processing your payment.</p>
    </div>
{% endblock content %}

payment/templates/payment/completed.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Payment Successful
{% endblock title %}

{% block breadcrumb %}
    Payment Completed
{% endblock breadcrumb %}

{% block content %}
    <div class="container text-center mt-5">
        <h1 class="mb-4">Your payment was successful</h1>
        <p>Your payment has been processed successfully.</p>
    </div>
{% endblock content %}

payment/templates/payment/process.html
{% extends "shop/base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}
    Pay your order
{% endblock title %}

{% block breadcrumb %}
    Order Summary
{% endblock breadcrumb %}

{% block content %}
    <!-- Order Confirmation Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th class="shoping__product">Products</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in order.items.all %}
                                    <tr>
                                        <td class="shoping__cart__item">
                                            <img src="{% thumbnail item.product.image 60x60 crop %}" alt="">
                                            <h5>{{ product.name }}</h5>
                                        </td>
                                        <td class="shoping__cart__price">${{ item.price }}</td>
                                        <td class="shoping__cart__quantity">{{ item.quantity }}</td>
                                        <td class="shoping__cart__total">${{ item.get_cost }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                {% if order.items.all|length > 0 %}
                    <div class="col-lg-6">
                        <div class="shoping__checkout">
                            <h5>Order Total</h5>
                            <ul>
                                {% if order.coupon %}
                                    <li>
                                        Subtotal <span id="cart-subtotal">${{ order.get_total_cost_before_discount|floatformat:2 }}</span>
                                    </li>
                                    <li>
                                        Discount ({{ order.discount }}% off) <span id="cart-discount">- ${{ order.get_discount|floatformat:2 }}</span>
                                    </li>
                                {% endif %}
                                <li>
                                    Total <span id="cart-total">${{ order.get_total_cost|floatformat:2 }}</span>
                                </li>
                            </ul>
                            <form action="{% url "payment:process" %}" method="post">
                                <input type="submit" value="Pay now" class="primary-btn">
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </section>
    <!-- Order Confirmation Section End -->
{% endblock content %}